server:
  port: 7004
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowCredentials: true
            allowedOrigins: "*" # 支持跨域，允许所有的域
            allowedMethods: "*" # 支持的方法,允许所有的方法
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: CLIENT01
          uri: lb://CLIENT01
          predicates:
            - Path=/CLIENT01/user/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true